name: brixmarket
description: Buy, Rent and Lease Properties in a safe space. Find Great Properties at Competitive Price.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.26+26

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sizer: ^2.0.15
  group_radio_button: ^1.3.0
  pin_code_fields: ^7.4.0
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  material_floating_search_bar_2:
  #flutter_paystack_client: ^0.1.0
  extended_image:
  shared_preferences: ^2.1.1
  device_info_plus: ^3.2.4
  intl: 
  image_picker: ^0.8.7+5
  file_picker:
  flutter_cors: ^1.3.2
  graphic: ^2.2.0
  path_provider: ^2.0.15
  carousel_slider: ^4.2.1
  universal_io:
  flutter_phone_direct_caller: ^2.1.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  share_plus:
  modal_bottom_sheet: ^3.0.0-pre
  firebase_database: ^10.2.0
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  cross_connectivity: ^3.0.5
  url_launcher: ^6.1.11
  flutter_widget_from_html_core: ^0.10.0
  flutter_local_notifications: 
  url_strategy: ^0.2.0
  change_app_package_name:
  firebase_remote_config: ^4.2.0
  firebase_dynamic_links: ^5.3.0
  cloud_firestore: ^4.7.0
  firebase_analytics: ^10.4.0
  firebase_auth: ^4.6.0
  firebase_storage: ^11.2.0
  youtube_player_flutter: ^8.1.2
  package_info_plus:
  another_xlider: ^3.0.1
  restart_app: ^1.1.2
  uni_links: ^0.5.1
  number_paginator: ^0.2.3
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2 # flutter pub run flutter_launcher_icons:main


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/brix-logo.png"

