name: brixmarket
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+9

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  sizer: ^2.0.15
  group_radio_button: ^1.2.0
  pin_code_fields: ^7.4.0
  flutter_rating_bar: ^4.0.0
  readmore: ^2.1.0
  material_floating_search_bar: ^0.3.7
  #flutter_paystack_client: ^0.1.0
  extended_image: ^6.0.2+1
  shared_preferences: ^2.0.6
  device_info_plus: ^3.2.3
  intl: ^0.17.0
  image_picker: ^0.8.5
  file_picker: ^4.5.1
  flutter_cors: ^1.3.2
  graphic: ^0.10.3
  path_provider: ^2.0.9
  carousel_slider: ^4.0.0
  universal_io: ^2.0.4
  flutter_phone_direct_caller: ^2.1.1
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  share_plus: ^4.0.4
  modal_bottom_sheet: ^2.0.1
  firebase_database: ^9.0.15
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  cross_connectivity: ^3.0.5
  url_launcher: ^6.1.3
  flutter_widget_from_html_core: ^0.8.5+3
  flutter_local_notifications: ^9.4.1
  url_strategy: ^0.2.0
  change_app_package_name:
  firebase_remote_config:
  firebase_dynamic_links: ^3.0.2
  cloud_firestore: ^3.1.7
  firebase_analytics:
  firebase_auth: ^3.3.6
  firebase_storage:
  youtube_player_flutter: ^8.0.0
  package_info_plus: ^1.0.2
  universal_html:
  another_xlider: ^1.1.2
  restart_app: ^1.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2 # flutter pub run flutter_launcher_icons:main


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/brix-logo.png"

